name: Build Windows EXE

on:
  # Run whenever you push to main or master in your fork
  push:
    branches: [ main, master ]
  # Allow running manually from the Actions tab
  workflow_dispatch:

jobs:
  CI:
    name: 'Windows Build'
    secrets: inherit
    uses: ./.github/workflows/lagom-template.yml
    with:
      toolchain: 'ClangCL'
      os_name: 'Windows'
      runner_labels: '["windows-2025"]'
      arch: 'x86_64'
      build_preset: 'Windows_CI'
      clang_plugins: false
